### ISSUE TITLE
Readme not descriptive

### ISSUE THREAD

**Issue by gsparsh220598** [param087/swiftML#36]
Please make the Readme.md more descriptive so new contributors can understand how to setup and test the codebase in their local system.

A step by step guide on how to install and test the libraries would be cool.

**Comment by gsparsh220598** [comment]
@param087 would you like to claim this since you have been contributing for a while?

**Comment by param087** [comment]
Hey,  I will push recent readme by EOD till then you can refer older readme from: https://github.com/param087/swiftML/blob/readme/README.md

**Comment by gsparsh220598** [comment]
Thanks for the readme
